export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const PURCHASE_STATUS = 'PURCHASE_STATUS';
export const FETCH_INGREDIENT = 'FETCH_INGREDIENT';
export const SET_INGREDIENT_FAILED = 'SET_INGREDIENT_FAILED';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAILED = 'ORDER_FAILED';
export const ORDER_START = 'ORDER_START';
export const PURCHASED_ORDER_HANDLER = 'PURCHASED_ORDER_HANDLER';

export const SHOW_ORDER_START = 'SHOW_ORDER_START';
export const SHOW_ORDER_SUCCESS = 'SHOW_ORDER_SUCCESS';
export const SHOW_ORDER_FAILED = 'SHOW_ORDER_FAILED';

export const DELETE_ORDER_ITEM_SUCCESS = 'DELETE_ORDER_ITEM_SUCCESS';
export const DELETE_ORDER_ITEM_FAILED = 'DELETE_ORDER_ITEM_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';
export const LOGOUT_HANDLER = 'LOGOUT_HANDLER';
export const AUTH_CHECK_STATUS = 'AUTH_CHECK_STATUS';

